var MSG = {
  title: "コード",
  blocks: "ブロック",
  linkTooltip: "ブロックの状態を保存してリンクを取得します。",
  runTooltip: "ブロックで作成したプログラムを実行します。",
  badCode: "プログラムのエラー:\n%1",
  timeout: "命令の実行回数が制限値を超えました。",
  trashTooltip: "すべてのブロックを消します。",
  catLogic: "ろんり",
  catLoops: "くりかえし",
  catMath: "けいさん",
  catText: "テキスト",
  catLists: "リスト",
  catColour: "色",
  catVariables: "へんすう",
  catFunctions: "かんすう",
  listVariable: "リスト",
  textVariable: "テキスト",
  httpRequestError: "ネットワーク接続のエラーです。",
  linkAlert: "ブロックの状態をこのリンクで共有できます:\n\n%1",
  hashError: "すみません。「%1」という名前のプログラムは保存されていません。",
  xmlError: "保存されたファイルを読み込めませんでした。別のバージョンのブロックリーで作成された可能性があります。",
  badXml: "XML のエラーです:\n%1\n\nXML の変更をやめるには「OK」、編集を続けるには「キャンセル」を選んでください。",
  saveTooltip: "ブロックをファイルに保存します。",
  loadTooltip: "ファイルからブロックを読み込みます。",
  notificationTooltip: "テキスト",
  ErrorGET: "リクエストされたファイルを読み込めません。",
  invalidDevice: "無効なデバイスです。",
  languageTooltip: "言語を変更する。",
  noToolbox: "デバイスにツールボックス セットがありません。",
  networkTooltip: "ネットワーク経由で接続します。(WebREPL、http)",
  serialTooltip: "シリアル/USB または Bluetoothを使用して接続します。(Web Serial API、https)",
  toolbarTooltip: "ツールバーを表示する。",
  wrongDevicePin: "ターゲット デバイスが変更されました、ピンを確認してください。",
  notDefined: "定義されていません",
  editAsFileValue: "ファイルを編集",
  editAsFileTooltip: "Pythonコードを編集し、デバイスのファイルに保存します。",
  forumTooltip: "プログラムの例",
  blocksLoadedFromFile: "ファイル '%1' のブロックをロードしました。",
  deviceUnavailable: "デバイス '%1' は使用できません。",
  notConnected: "データを送信するための接続がありません。",
  serialFroozen: "シリアル接続が応答しません。",
  notAvailableFlag: "$1 はお使いのブラウザでは利用できません。\r\n$1 フラグが有効になっていることを確認してください。"

};

